// Office art v2.1 manifest (generated by scripts/office-art/v2/build.mjs).
// Two sets with identical sprite/state keys: cozy («Мастерская», light theme) and neon («Неоновый хаб», dark theme).
// Superset of OfficeArtManifestV1: same sprites/states/frames/anchor/hitRect, plus the fields below.

export type OfficeArtSet = 'cozy' | 'neon'
export const OFFICE_ART_SET_BY_THEME = { light: 'cozy', dark: 'neon' } as const satisfies Record<'light' | 'dark', OfficeArtSet>
export type OfficeArtAtlasV2 = 'tiles' | 'furniture' | 'agents' | 'roles' | 'effects' | 'font'
export type RGB = [number, number, number]
export interface RectV2 { x: number; y: number; width: number; height: number }
export interface PointV2 { x: number; y: number }

export interface OfficeArtFrameV2 {
  rect: RectV2
  anchor: PointV2
  hitRect: RectV2
  /** Same-size rect in the same atlas: draw it AFTER the light map, unlit (screens, LEDs, neon, overlays). */
  emit?: RectV2
}
export interface OfficeArtAnimationV2 { frames: OfficeArtFrameV2[]; durationsMs: number[]; loop: boolean }
/** Light pool added to the light map at anchor + (dx, dy); only for the listed states when `states` is set. */
export interface OfficeArtLight { dx: number; dy: number; rx: number; ry: number; color: RGB; k: number; states?: string[] }
export interface OfficeArtSpriteV2 {
  atlas: OfficeArtAtlasV2
  /** First layer decides the order within the same anchor Y; floor/floor-shade/rug are drawn before the Y-sorted pass. */
  layers: string[]
  states: Record<string, OfficeArtAnimationV2>
  lights?: OfficeArtLight[]
  /** Named points/rects relative to the sprite anchor (bench seats, plaques, hands, desk plaque…). */
  slots?: Record<string, PointV2 | RectV2>
}
export interface OfficeArtNineSlice {
  sprite: string; state: string; left: number; right: number; height: number
  textX?: number; textY?: number; markX?: number; markY?: number; maxWidth?: number; scale?: number
  /** Font colour row to print with. */
  font?: string
}
export interface OfficeArtFont {
  atlas: 'font'; height: number; spacing: number; space: number; fallback: string
  /** Y offset of each colour row in font.png: ink, light, sign, warn, dim. */
  colors: Record<string, number>
  /** Glyph rects at the ink row; add colors[c] to y. Lowercase → uppercase before lookup. */
  glyphs: Record<string, { x: number; y: number; w: number }>
}
export interface OfficeArtManifestV2 {
  version: 2
  set: OfficeArtSet
  theme: 'light' | 'dark'
  tile: { width: 16; height: 16 }
  character: { width: 32; height: 48; anchor: { x: 16; y: 44 } }
  atlases: Record<OfficeArtAtlasV2, { file: string; width: number; height: number }>
  layers: string[]
  lighting: Record<string, unknown> & { ambient: RGB; steps: number; dither: 'bayer4'; glowSprites: boolean }
  palette: Record<string, unknown> & { status: Record<string, string>; link: string; user: string; attempt: string; cable: string[]; packet: string; linkStyle: 'dotted' | 'beam' }
  font: OfficeArtFont
  nineSlices: Record<string, OfficeArtNineSlice>
  /** Zone contents (lounge, head, wall, lobby, server, boss, corridor, outside, pet, timeOfDay). See OFFICE-V21-ART.md. */
  compositions: Record<string, unknown>
  sprites: Record<string, OfficeArtSpriteV2>
}
